from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('agile_serial', src, depend = ['PKG_USING_AGILE_SERIAL'], CPPPATH = CPPPATH)

Return('group')
